global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'banking-prod'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules
rule_files:
  - '/etc/prometheus/rules/*.yml'
  - '/etc/prometheus/alerts/*.yml'

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 10s

  # demo Application - Kubernetes
  - job_name: 'bankcore-k8s'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - banking-prod
            - banking-staging
    relabel_configs:
      # Only scrape pods with prometheus annotation
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      # Use custom port if specified
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
      # Use custom path if specified
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      # Add pod labels
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
      - source_labels: [__meta_kubernetes_pod_node_name]
        action: replace
        target_label: kubernetes_node

  # demo Application - VM
  - job_name: 'bankcore-vm'
    static_configs:
      - targets:
          - 'vm1.bankcore.com:8080'
          - 'vm2.bankcore.com:8080'
        labels:
          environment: 'production'
          deployment_type: 'vm'
    metrics_path: /actuator/prometheus
    scrape_interval: 30s
    scrape_timeout: 10s

  # Kubernetes components
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
      - role: endpoints
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https

  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)

  # Node exporter for VMs
  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - 'vm1.bankcore.com:9100'
          - 'vm2.bankcore.com:9100'
        labels:
          environment: 'production'

  # PostgreSQL exporter
  - job_name: 'postgres'
    static_configs:
      - targets:
          - 'postgres.bankcore.com:9187'
        labels:
          environment: 'production'
          service: 'postgresql'

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets:
          - 'redis.bankcore.com:9121'
        labels:
          environment: 'production'
          service: 'redis'

  # NGINX exporter
  - job_name: 'nginx'
    static_configs:
      - targets:
          - 'nginx.bankcore.com:9113'
        labels:
          environment: 'production'
          service: 'nginx'

  # Blackbox exporter for endpoint monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://bankcore.com/api/v1/health
          - https://bankcore.com/actuator/health
          - https://vm.bankcore.com/api/v1/health
        labels:
          probe_type: 'http'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

# Remote storage configuration (optional)
# remote_write:
#   - url: "http://cortex:9009/api/v1/push"
#     queue_config:
#       capacity: 10000
#       max_shards: 30
#       min_shards: 1
#       max_samples_per_send: 5000
#       batch_send_deadline: 5s
#       min_backoff: 30ms
#       max_backoff: 100ms

# Remote read configuration (optional)  
# remote_read:
#   - url: "http://cortex:9009/api/v1/read"
#     read_recent: true