apiVersion: v1
kind: ServiceAccount
metadata:
  name: bankcore
  namespace: banking-prod
  labels:
    app: bankcore
    component: backend
  annotations:
    kubernetes.io/description: "Service account for bankcore application"